Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

=== RESTART: C:\Users\HP\AppData\Local\Programs\Python\Python310\assign 4.py ===
Move disk 1 from source A to destination C
Move disk 2 from source A to destination B
Move disk 1 from source C to destination B
Move disk 3 from source A to destination C
Move disk 1 from source B to destination A
Move disk 2 from source B to destination C
Move disk 1 from source A to destination C
Move disk 4 from source A to destination B
Move disk 1 from source C to destination B
Move disk 2 from source C to destination A
Move disk 1 from source B to destination A
Move disk 3 from source C to destination B
Move disk 1 from source A to destination C
Move disk 2 from source A to destination B
Move disk 1 from source C to destination B
      1
     1 1
    1 2 1
   1 3 3 1
  1 4 6 4 1
Enter 2 numbers: 57 28
a. Checking if the quotient and remainder is a callable value or not.
False
False
<b> All the values are non zero
<c> Filtered out numbers that are greater than 4 are : [6, 5, 6, 7, 6, 8, 7]
<d> Set: {8, 5, 6, 7}
<e> Immutable set: frozenset({8, 5, 6, 7})
<f> Hash value of the max value from the above set:  8
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\assign 4.py", line 80, in <module>
    employee1 = Employee("Mehak", 40000)
TypeError: Employee() takes no arguments
